# Generated by Django 3.0.2 on 2021-02-23 20:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210224_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digit number only, number should not start with 1, 2, 3, 4,or 5.', regex='^[6-9][0-9]{9}$')]),
        ),
    ]
