# Generated by Django 3.0.2 on 2021-02-20 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buisness',
            fields=[
                ('name', models.CharField(auto_created=True, max_length=100, serialize=False)),
                ('id', models.AutoField(default=10000, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='default.jpg', upload_to='orders')),
                ('ordered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
