# Generated by Django 3.0.2 on 2021-02-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210220_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buisness',
            name='user',
        ),
    ]
