# Generated by Django 3.0.2 on 2021-02-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_buisness_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buisness',
            name='id',
            field=models.IntegerField(default=10000, primary_key=True, serialize=False),
        ),
    ]
