# Generated by Django 3.0.2 on 2021-02-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210220_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buisness',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
