# Generated by Django 3.0.2 on 2021-02-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210220_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buisness',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
