# Generated by Django 3.0.2 on 2021-02-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210220_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buisness',
            name='id',
            field=models.IntegerField(default=10001, primary_key=True, serialize=False),
        ),
    ]
