# Generated by Django 3.0.2 on 2021-02-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210220_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buisness',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
