# Generated by Django 3.0.2 on 2021-02-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210220_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buisness',
            name='image',
        ),
    ]
